# Generated by Django 3.1.4 on 2024-04-20 20:23

import cleaning.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cleaning',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('serviceurl', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('image', models.ImageField(upload_to=cleaning.models.image_upload)),
            ],
        ),
    ]
