# Generated by Django 3.1.4 on 2024-04-23 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demolish', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demolish',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='demolish',
            name='note',
        ),
    ]
