# Generated by Django 3.1.4 on 2024-04-23 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demolish', '0003_demolish_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='demolish',
            name='full_name',
            field=models.CharField(default=1, max_length=200, verbose_name='First and Last Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='demolish',
            name='note',
            field=models.CharField(max_length=1000, verbose_name='Enter Your Notic'),
        ),
    ]
