# Generated by Django 3.1.4 on 2024-04-20 20:23

from django.db import migrations, models
import moving.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moving',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('serviceurl', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('image', models.ImageField(upload_to=moving.models.image_upload)),
            ],
        ),
    ]
